name:               "ArkSec"
description:        "IT security and proof of concepts"

url:                ""
author:             "ark"
email:              "quentrg@gmail.com"
gravatar_hash:      "af9c07b77fee746d0e34622857671a03"
twitter:            "Ark_444"
email:              "quentrg@gmailcom"
github:             "Ark444"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "arkxor"

background:         "images/background.png"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:day/:month/:year/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
