# Site settings
title: "ArkSec"
url: ""    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
    IT security and proof of concept.    

# Your information
email: quentrg@gmail.com
author: ark
avatar: "//www.gravatar.com/avatar/af9c07b77fee746d0e34622857671a03?d=mm&s=135"
profile: 
twitter_username: Ark_444
github_username: Ark444

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: "ark444-github-io" # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

banner: "/images/banner.bmp"

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
